# 0. intro
1. https://www.bilibili.com/video/BV18g4119737/?p=31&spm_id_from=pageDriver&vd_source=70200f7d09862fd682e5f89b22c89125
2. 统计属性：
    - norm
    - mean sum
    - prod
    - max,min,argmin,argmax
    - kthvalue,topk

In [3]:
import torch

# 1. 范数norm
1. 是范数不是正则化
2. matrix norm和vector norm
    - 多用后者

In [10]:
a=torch.full([8],1.)
b=a.view(2,4)
print(f"b:{b}")

b:tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
c:tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])


In [11]:
a.norm(1),b.norm(1)

(tensor(8.), tensor(8.), tensor(8.))

In [13]:
#8**(0.5)
a.norm(2),b.norm(2)

(tensor(2.8284), tensor(2.8284), tensor(2.8284), 2.8284271247461903)

In [14]:
b.norm(1,dim=1)

tensor([4., 4.])

In [15]:
b.norm(2,dim=1)

tensor([2., 2.])

# 2. 常用运算
1. `prod`:返回给定维度 dim 中 input 张量的每一行的乘积。
2. `argmax` `argmin`返回的是下标
    - 而且会先把`a`打平成一个vector，然后返回索引
    - 不希望打平需要参数`dim`

In [25]:
a=torch.arange(8).view(2,4).float()
a

tensor([[0., 1., 2., 3.],
        [4., 5., 6., 7.]])

In [27]:
a.min(),a.max(),a.mean(),a.prod(),a.sum()

(tensor(0.), tensor(7.), tensor(3.5000), tensor(0.), tensor(28.))

In [28]:
a.argmin(),a.argmax()

(tensor(0), tensor(7))

In [32]:
a=torch.randn(4,10)
print()
print(a.argmax())
print(a.argmax(dim=1))



tensor(3)
tensor([3, 1, 7, 5])


# 3. dim和keepdim
1. `a`表示4张照片，10个分类，因此一个照片对应了10个预测置信度，此时要寻找最大的分类是哪个及其对应的概率值
2. `keepdim=True`时，并不做`squeeze`的操作

In [35]:
a=torch.randn(4,10)
print(a)
# 前面的数字是value后面的数字是下标
print(a.max(dim=1))

tensor([[-2.0155, -1.9601, -0.6398, -0.2628,  0.8060, -0.2826, -0.4652,  0.4693,
          1.8985, -0.1764],
        [ 0.4289,  1.0759, -1.7544,  1.5490, -1.9964, -0.2590, -0.2805,  0.0518,
          1.7375, -1.4277],
        [ 0.9108,  0.5244, -1.6860,  1.7950, -1.7996, -0.8249,  0.1810,  0.4719,
         -0.5351, -1.2075],
        [-0.2678, -0.3797,  1.8906, -1.7042,  0.2277,  2.1196,  0.0288,  0.9136,
          1.1492, -0.3673]])


torch.return_types.max(
values=tensor([1.8985, 1.7375, 1.7950, 2.1196]),
indices=tensor([8, 8, 3, 5]))

此时a.max或者a.argmax的返回值的shape是：

In [38]:
a.argmax(dim=1).shape

torch.Size([4])

但是如果`keepdim=True`，就会是:，并不做`squeeze`的操作

In [39]:
a.argmax(dim=1,keepdim=True).shape

torch.Size([4, 1])

# 4. Top-k or k-th
1. `topk`得到最大的`n`个值及其下标
    - 最小的几个需要`largest=False`
2. `kthvalue`得到第`n`小的值，**而且只能获得“小”**

In [41]:
print(a)
print(a.topk(3,dim=1))
print(a.topk(3,dim=1,largest=False))
print(a.kthvalue(8,dim=1))

tensor([[-2.0155, -1.9601, -0.6398, -0.2628,  0.8060, -0.2826, -0.4652,  0.4693,
          1.8985, -0.1764],
        [ 0.4289,  1.0759, -1.7544,  1.5490, -1.9964, -0.2590, -0.2805,  0.0518,
          1.7375, -1.4277],
        [ 0.9108,  0.5244, -1.6860,  1.7950, -1.7996, -0.8249,  0.1810,  0.4719,
         -0.5351, -1.2075],
        [-0.2678, -0.3797,  1.8906, -1.7042,  0.2277,  2.1196,  0.0288,  0.9136,
          1.1492, -0.3673]])
torch.return_types.topk(
values=tensor([[1.8985, 0.8060, 0.4693],
        [1.7375, 1.5490, 1.0759],
        [1.7950, 0.9108, 0.5244],
        [2.1196, 1.8906, 1.1492]]),
indices=tensor([[8, 4, 7],
        [8, 3, 1],
        [3, 0, 1],
        [5, 2, 8]]))
torch.return_types.topk(
values=tensor([[-2.0155, -1.9601, -0.6398],
        [-1.9964, -1.7544, -1.4277],
        [-1.7996, -1.6860, -1.2075],
        [-1.7042, -0.3797, -0.3673]]),
indices=tensor([[0, 1, 2],
        [4, 2, 9],
        [4, 2, 9],
        [3, 1, 9]]))


# 5. compare
1. \>, gt(a,0), a!=0, eq(a,b) 都是对每个位置元素的比较
2. 常用判断两个是否相等：`torch.all(torch.eq(a,b)`返回的是一个true or false的值

# 6. 有助于理解dim

In [ ]:
b = torch.tensor([1.,2.,3.,4.,5.,6.])
b = b.view(2,3)
b.norm(2,dim=0)