In [1]:
import torch

# 1. where
1. 不规则的，有条件的赋值，用`for`也可以但是并行化较差，where可以用gpu

In [4]:
cond = torch.randn(2,2)
cond

tensor([[-0.1705, -1.7568],
        [-2.1810,  1.6128]])

In [6]:
a = torch.zeros(2,2)
a

tensor([[0., 0.],
        [0., 0.]])

In [7]:
b = torch.ones(2,2)
b

tensor([[1., 1.],
        [1., 1.]])

In [8]:
torch.where(cond>0.5,a,b)

tensor([[1., 1.],
        [1., 0.]])

# 2. gather
1. 有一个category：[dog,cat,whale]，每一张图片会判断照片属于哪个类别，因此每一个照片有一个概率对应了这3个类别的概率，
2. 以4张照片为例，用`argmax`可以取出概率最大照片的下标如[0,1,1,2]
3. `gather`可以进一步把[0,1,1,2]返回成[dog,cat,cat,whale]
    - 实际上是一个**查表操作**
    - 完成了从计算下标到实际下标的映射

In [10]:
prob=torch.randn(4,10)
prob

tensor([[-1.7024, -1.6264, -1.0976, -1.7972, -0.5500,  0.7170,  0.8832,  0.2162,
          0.7950,  0.0188],
        [ 1.0856, -0.4972, -0.8687,  0.9777,  0.3078, -0.4866, -0.9426,  0.4876,
          0.4875,  1.4660],
        [-0.9555,  1.2976,  1.2459, -0.6340,  0.0740, -0.9348, -1.8054, -0.3189,
          0.6212,  0.3967],
        [-1.4199, -0.9082, -1.5998, -1.0420, -0.4997,  0.0201, -1.1939, -0.8466,
          1.1811, -1.0453]])

In [18]:
idx = prob.topk(dim=1,k=3)[1]
idx,idx.shape

(tensor([[6, 8, 5],
         [9, 0, 3],
         [1, 2, 8],
         [8, 5, 4]]),
 torch.Size([4, 3]))

In [16]:
# 图片的实际编号，不是（0,10）这种范围
label = torch.arange(10)+100
label

tensor([100, 101, 102, 103, 104, 105, 106, 107, 108, 109])

4. 使用的时候，先扩张label的大小，然后要确定好dim，

In [17]:
torch.gather(label.expand(4,10), dim=1, index = idx.long())

tensor([[106, 108, 105],
        [109, 100, 103],
        [101, 102, 108],
        [108, 105, 104]])